FORMAT: 1A
HOST: http://iot-weather.herokuapp.com/webapi

# iot-weather

iot-weather is a simple API, which helps you get some weather information.

## Ping [/ping]

### Ping Service [GET]

Returns html status code 200, if the server is alive.

+ Response 200 (application/json)


## Temperature [/houses/{house_id}/temperature]

### Get Current Temperature [GET]

if house_id is valid returns current temperature in celsius and farenheit.
if house_id is not valid returns error 400.

+ Parameter
    + house_id (required, string, `a1bc00fb-4724-476a-a553-d65d2c1bac0e`)
    String returned in Location header field.
    
+ Request (application/json)

+ Response 200 (application/json)

            {
                "temp_c": "15",
                "temp_f": "59"
            }

+ Request (application/json)

+ Response 400 (application/json)

## Rain [/houses/{house_id}/rain]

### Get Next 24 Hours Raining Forecast [GET]

if house_id is valid returns "yes" or "no" whether it will rain in the next 24 hours.
if house_id is not valid returns error 400.

+ Parameter
    + house_id (required, string, `a1bc00fb-4724-476a-a553-d65d2c1bac0e`)
    String returned in Location header field.

+ Request (application/json)

+ Response 200 (application/json)

            {
                "rain": "yes"
            }

+ Request (application/json)

+ Response 400 (application/json)
