FORMAT: 1A
HOST: http://iot-weather.herokuapp.com/webapi

# iot-weather

iot-weather is a simple API, which helps you get some weather information.

## Ping [/ping]

### Ping Service [GET]

Returns html status code 200, if the server is alive.

+ Response 200 (application/json)


## Temperature [/temperature]

### Get Current Temperature [GET]

returns current temperature in celsius and farenheit.

+ Response 200 (application/json)

        [
            {
                "temp_c": "15",
                "temp_f": "59"
            }
        ]

## Rain [/rain]

### Get Next 24 Hours Raining Forecast [GET]

returns "yes" or "no" whether it will rain in the next 24 hours.

+ Response 200 (application/json)

        [
            {
                "rain": "yes"
            }
        ]